name: pangeo
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - fastqc ==0.11.9
  - multiqc ==1.10.1
  - trimmomatic ==0.36
  - pigz ==2.3.4
  - bwa ==0.7.17
  - samtools ==1.9
  - picard ==2.20.1
  - r-base=3.6
  - r-tidyverse
  - bcftools ==1.12
  - gatk4 ==4.1.4.1
  - vcftools ==0.1.16
  - ncurses==6.2
  - python==3
  - readline==8.1
